# -*- coding: utf-8 -*-
"""py_collections_lists_tuples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zn6ymIQi8fgT7Vy5ooei_WRRc7wTUliV

# Listas e Operacoes
"""

age_01 = 39
age_02 = 30
age_03 = 27
age_04 = 18

print(age_01)
print(age_02)
print(age_03)
print(age_04)

ages = [39, 30, 27, 18]
type(ages)

len(ages)

ages[0]

ages

ages.append(15)

ages

ages[4]

for age in ages:
  print(age)

ages.remove(30)

ages

ages.append(15)

ages

ages.remove(15)

ages

ages.append(27)
ages.remove(27)
ages

28 in ages

15 in ages

if 15 in ages:
  ages.remove(15)

ages

ages.clear()
ages

ages = [39, 18, 15, 27]
ages

"""*Adicionando elementos em uma lista :*

```
# Adicionando 1 elemento em 1 posicao 
```
"""

ages.insert(0, 20)
ages

"""

```
# Adicionando varios elementos em 1 lista, ou elementos de uma lista em outra lista.
```

"""

new_ages = [19, 21, 40]
ages.extend(new_ages)
ages

"""
```
# Descobrindo idades do proximo ano
```
"""

ages_next_year = []
for age in ages:
    ages_next_year.append(age + 1)
ages_next_year

"""

```
# List comprehension
```

"""

ages_next_year = [(age + 1) for age in ages]
ages_next_year

[(age) for age in ages if age > 21]

def next_year(age):
  return age + 1

[next_year(age) for age in ages if age > 21]

"""# Tuplas"""

class CorrentAccount:

  def __init__(self, code):
    self.code = code
    self.balance = 0

  def deposit(self, value):
    self.balance += value
  
  def __str__(self):
    return (f" Code: {self.code} >> Balance: {self.balance}")

account_01 = CorrentAccount(15)
print(account_01)

account_02 = CorrentAccount(5121)
print(account_02)

accounts = [account_01, account_02]
print(accounts)

for account in accounts:
  print(account)

account_01.deposit(100)
account_02.deposit(500)

for account in accounts:
  print(account)

def deposit_for_all_accounts(accounts):
  for account in accounts:
    account.deposit(100)

accounts = [account_01, account_02]
print(accounts[0], accounts[1])
deposit_for_all_accounts(accounts)
print(accounts[0], accounts[1])

"""
```
# Para sequencia de elementos com tipos diferentes que nao sao mutaveis ultilizamos tupla. (posicao especificas, coisas diferentes)
```

"""

igor = ('Igor', 20, 2000)  # tupla
amanda = ('Amanda', 20, 2001)

# Paulo = (39, 'Paulo', 1998) # ruim

igor.append(5123)

account_01 = (15, 1000)
# account_01.deposit() # variacao OO

print(account_01[1])

account_01[1] += 10

def deposit(account): # Modelo Procedural (Separando comportamento dos dados)
  new_balance = account[1] + 100
  code = account_01[0]
  return (code, new_balance)

account_01

account_01 = deposit(account_01)
account_01

users = [igor, amanda]
users

users.append(('Paulo', 21, 1999))
users

account_01 = CorrentAccount(15)

accounts = (account_01, account_02) # tuplas de objetos (podemos mudar o objeto, mas a tupla nao)

for account in accounts:
  print(account)

accounts[1].deposit(500)

accounts

for account in accounts:
  print(account)